Feature/about
kovlanproj/team-project pull request #5
Opened 2022-07-14 17:39 UTC by KRiabchenko

Add adaptive images and section about

2022-07-14 17:58 UTC, kovlanproj requested changes
1. Неправильно указані адреси до зображень
має бути не ../images/cow-des-1x.png 1x,
а images/cow-des-1x.png 1x
2. Не використаний контейнер.

2022-07-14 19:58 UTC, KRiabchenko commented
1 і 3 пункт виправила, з приводу 2 наче в мене немає контейнеру. Ще додала svg до кнопки, переглянь будь-ласка.

2022-07-15 07:36 UTC, kovlanproj commented
> 1 і 3 пункт виправила, з приводу 2 наче в мене немає контейнеру. Ще додала svg до кнопки, переглянь будь-ласка.
Так, але ж він має бути. Потрібно секцію обгорнути в контейнер, щоб контент не розповзався. В файлі _container.scss прописаний клас.

2022-07-16 07:20 UTC, KRiabchenko commented
Обгорнула в контейнер, переглянь будь-ласка.

2022-07-16 07:37 UTC, kovlanproj requested changes
в десктоп версії молоко не прилягає до країв при ширині 1200px Потрібно поправити, щоб при ширині 1200 воно прилягало, а при ширині більше ніж 1200 не розтягувалось.
![Screenshot_2](https://user-images.githubusercontent.com/104130825/179345267-959ccd6c-9ba5-47b6-9708-2fd34561e214.png)

властивість line-height для тексту не відповідає макету у всіх версіях верстки
font-size для другого абзацу в десктопній версії не відповідає макету

2022-07-16 12:05 UTC, KRiabchenko commented
line-height і font-size я передивилась, я указувала у відносній велечині (line-height/font-size), чи треба в px?
У мене не виходить зробити молоко по краях, через контейнер. Коли всю секцію роблю в контейнер, то bg-колір не тягнеться, а коли все окрім секціі, то молоко реагує на падінги контейнера. Не підкажеш, як бути?

2022-07-16 13:08 UTC, kovlanproj commented
> line-height і font-size я передивилась, я указувала у відносній велечині (line-height/font-size), чи треба в px? У мене не виходить зробити молоко по краях, через контейнер. Коли всю секцію роблю в контейнер, то bg-колір не тягнеться, а коли все окрім секціі, то молоко реагує на падінги контейнера. Не підкажеш, як бути?

По контейнеру скинув в Телеграм.
line-height і font-size я просто дивився і у мене не співпадало. Може я глюканув. Пізніше гляну ще. У відносних величинах - правильно

2022-07-16 14:42 UTC, KRiabchenko commented
Все вийшло, запушила. Дякую за допомогу))

2022-07-16 15:01 UTC, kovlanproj approved these changes

2022-07-16 15:01 UTC, merged